name: publish

on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: audit
        run: |
          pnpm i --frozen-lockfile
      #          pnpm audit
      - name: versioning
        run: pnpm exec lerna version minor -y
      # -y
      # peer dependencies alles mit JSON Forms updaten
      # z.B mit node scrips
