name: publish

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: 'version'
        required: true
        default: 'minor'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: audit
        run: |
          pnpm i --frozen-lockfile
      #          pnpm audit
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: versioning
        run: pnpm exec lerna version ${{ github.event.inputs.next_version }} --no-push --force-publish -y

      - name: adjust peerDependencies
        run: cd packages/angular && pnpm pkg set peerDependencies.@jsonforms/core="${{ github.event.inputs.next_version }}"

      #- name: adjust peer dependencies
      #  uses: jacobtomlinson/gha-find-replace@v3
      #  with:
      #    find: '(?<=.)("@jsonforms\/core": ".*")'
      #    replace: '@jsonforms/core": "${{ github.event.inputs.next_version }}"'
      #    regex: true

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: githubaction_publish

      # peer dependencies alles mit JSON Forms updaten
      # z.B mit node scrips
